ysbaddaden/sdl.cr

src/image.cr

Fixed typo in `BMP`, and added missing `JPG` according to https://www.libsdl.org/projects/SDL_image/docs/SDL_image.html#SEC10

Fixing Image Type

---

src/events.cr

I noticed that the call to `fingerID` was incorrect, so I fixed it.
I also removed a `then` as `crystal tool format` was removing it. I didn't remove the empty lines between `when` clauses as I believe you are using them for grouping.
Let me know if this isn't the way you would like me to issue the pull request as there are no contribution guidelines in your README.

Resolve duplicate SDL::Event::TouchFinger#touch_id

---

.gitignore
src/image.cr

This commit ignores Mac's `.DS_Store` file as well the `samples/data` folder which contains all the sample images. This will help to keep the images locally for testing samples but without accidentally adding them in to the repo

Ignore a few things

---

src/renderer.cr

The Y-value from the second point was used for both points.

Fix: draw_lines(x1, y1, x2, y2) had a typo

---

src/window.cr

Right now it gives you this when you use it:
```Crystal
Error in wool.cr:46: instantiating 'Wool::Window:Module#fullscreen(Bool)'
Wool::Window.fullscreen true
^~~~~~~~~~
in window.cr:29: instantiating 'SDL::Window#fullscreen=(Bool)'
window.fullscreen = true
^~~~~~~~~~
in lib/sdl/src/window.cr:86: undefined constant LibSDL::WindowFlags::WINDOW
self.fullscreen = value ? LibSDL::WindowFlags::FULLSCREEN : LibSDL::WindowFlags::WINDOW
^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Fix SDL::Window#fullscreen

---

src/lib_sdl/video.cr

SDL_GetWindowWMInfo can be used like so: 
window = SDL::Window.new("Window", 640, 480)
renderer = SDL::Renderer.new(window)
win_info = LibSDL::SDL_WMInfo.new
win_info.version.major = 2
win_info.version.minor = 0
win_info.version.patch = 1
if LibSDL.get_window_wm_info window, pointerof(win_info)
puts "SUCCESS!"
else
puts "FAILED?"
end
puts win_info
I also added 5 additional x11 specific window flags.

Added SDL_GetWindowWMInfo support, and additional window flags

---

src/lib_sdl/mouse.cr

From the [docs](https://wiki.libsdl.org/SDL_GetMouseState): 
> The current button state is returned as a button bitmask [...] and **x** and **y** are set to the mouse cursor position relative to the focus window for the currently selected mouse.

Fix SDL_GetMouseState binding

---

src/lib_sdl/video.cr

Exposes SDL function SDL_GetDisplayUsableBounds under name get_display_usable_bounds.
API is same as SDL_GetDisplayBounds, however function returns usable screen size rather than full screen size.

Expose SDL_GetDisplayUsableBounds

---

src/lib_sdl/keycode.cr

Things like `SDL::Event.poll.mod.lctrl?` won't work when several modifiers are active otherwise.
(Checking for `SDL::Event::Keyboard` is implied and omitted.)

Mark bitfield enum with `@[Flags]`

---

shard.yml

While `crystal` [attribute](https://github.com/crystal-lang/shards/blob/master/docs/shard.yml.adoc#optional-attributes) is marked "optional", `shards` assumes it to be `< 1.0.0` when missing and fails to install with the following error:
```
Unable to satisfy the following requirements:
- `crystal (< 1.0.0)` required by `sdl 0.1.0+git.commit.b674fbaaf9ff8505b3e76cbd43528d2f0cfdbdc2`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.
```
See if this version range seems legit for you.

Support Crystal 1.0.0 onwards, perhaps?

---

src/lib_sdl/video.cr

For…
```cr
window = SDL::Window.new("SDL", 640, 480)
renderer = SDL::Renderer.new(window)
puts LibSDL.get_window_flags(window)
```
…turns…
```
```
…into…
```
```

Marked WindowsFlags as a flags bitfield.

---

src/lib_sdl/video.cr

https://wiki.libsdl.org/SDL_WindowEventID

Add remaining WindowEventIDs

---

src/renderer.cr

Fixed a typo in `clip_rect` getter. Also, SDL lets you pass `null` to `SDL_RenderSetClipRect` and `SDL_RenderSetViewport`, so I switched both calls to them to a `pointer_or_null` call.

Quick fix for clip rects

---

src/pixels.cr

PixelFormat is returning the same value as `bits_per_pixel` in the `bytes_per_pixel` method.

Fix bytes_per_pixel method

---

src/events.cr

The scancode represents the physical key press, which is useful for preserving keymaps on different keyboard layouts (Dvorak/qwerty, etc)
This PR just adds a method to expose the scancode from the event

Add support for Event::Keyboard scancode

---

src/lib_sdl/pixels.cr
src/texture.cr

It appears that the macros which were ported from the SDL headers to define `PixelFormatEnum` don't work within the `enum` block (if anyone knows why, I'd love to learn about what is wrong there).
This PR replaces the macro call with the expanded values which are required to when using `LibSDL.create_texture`, and implements the `SDL::Texture#lock` method which yields a `Slice` pointing to the pixels buffer.

Allow streaming texture pixel access

---

src/lib_sdl/audio.cr

Looks like the callback in the `AudioSpec` struct should not be a pointer. I get an infinite recursion crash when trying to use it, but when it's not a pointer it works as expected.
I also ran crystal tool format on this file to convert some of the tabs to spaces, etc. but the actual change is just on line 51.

Change AudioSpec callback not to be a pointer

---

src/renderer.cr

It looks like `info` is not a pointer, and calling `value` on it raises a `NoMethodError`

Fix Renderer.info method

---

src/ttf.cr

* Renamed `size_ascii()` function calls to `size_text()`.
* Multiple `out` usage with the same name was causing multiple variable definitions. Replaced with explicit variables.

Fix text size methods

---

src/rect.cr

SDL has `SDL_PointInRect()`, but we cannot call it since it is inlined.

Add Rect.includes?()

---

src/ttf.cr

The related functions may return any non-zero value, but some code was testing with `== 1`. In my case, this was causing practical issues with `glyph_provided?`/`TTF_GlyphIsProvided()`, which was reporting almost all supported characters of a font as unsupported. Your mileage may vary.

Fix boolean checks for TTF functions
